### ISSUE TITLE
command in Batocera system terminal not working?

### ISSUE THREAD

**Issue by Classicdubs** [Gr3gorywolf/batocera_wine_manager#2]
I have tried the script a few time to get wine manager installed, and it seems to not want to go through with the install, I get an error.  Any ideas?

Chris

**Comment by Gr3gorywolf** [comment]
Can you send me a picture of the error?, also, what batocera version are you using??

**Comment by Classicdubs** [comment]
See attached!  Thanks for getting back to me.

Chris Vallone
www.ClassicVWbugs.com
See us on CBS Morning News
https://youtu.be/pxTTlN1ZSeY

**Comment by Gr3gorywolf** [comment]
I see no attachment :,v

**Comment by Classicdubs** [comment]
how bout now?

---
Chris Vallone
HoP into a BuG!
www.ClassicVWbugs.com

**Comment by Gr3gorywolf** [comment]
nope, submit it to imgurl and paste the link

**Comment by Classicdubs** [comment]
maybe the image was too big, let me shrink the size...

Chris Vallone
www.ClassicVWbugs.com
See us on CBS Morning News
https://youtu.be/pxTTlN1ZSeY

**Comment by Classicdubs** [comment]
Attached again..  

Please let me know

Chris Vallone
www.ClassicVWbugs.com
See us on CBS Morning News
https://youtu.be/pxTTlN1ZSeY

**Comment by Classicdubs** [comment]
or here https://www.classicvwbugs.com/wp-content/uploads/2024/06/PXL_20240603_190218396-scaled.jpg

Chris Vallone
www.ClassicVWbugs.com
See us on CBS Morning News
https://youtu.be/pxTTlN1ZSeY

**Comment by Gr3gorywolf** [comment]
gotcha, working on it, thanks for the patient

**Comment by Gr3gorywolf** [comment]
I'm dealing with it, I got a workaround, use a old install url which is cdn.gregoryc.dev/wine-manager and it should work

**Comment by Gr3gorywolf** [comment]
done, a silly server config issue!, try again with either cdn. or links.

**Comment by Classicdubs** [comment]
Ok thank you.  Do you have a video or anything on how to apply the wines to games?

Chris

⁣Get TypeApp for Android ​

**Comment by Gr3gorywolf** [comment]
There's no way to apply a per game proton versión before batocera v40, after batocera v40 on the game settings you select one of the installed wine versions

**Comment by Classicdubs** [comment]
Perfect!  Who's better than you man?! 
I have 40 installed, thank you 👍.

Chris 

⁣Get TypeApp for Android ​

**Comment by Classicdubs** [comment]
How many wines should I download?  

Chris 

⁣Get TypeApp for Android ​

**Comment by Classicdubs** [comment]
So I just updated to the latest Batocera 40 beta, and now all of my wine options are not in the list anymore.  The ones that I have installed already are there, but the other versions I did not install yet are off the list now. Should I reinstall wine manager? 

Chris 

⁣Get TypeApp for Android ​

**Comment by Gr3gorywolf** [comment]
Just download any of the wine versions using wine manager, then it should show up on the list, if not, restart the system

**Comment by Classicdubs** [comment]
You recommend installing the game in Batocera? Or should I install it in Windows and then drag the folder over to Batocera? 

Chris 

⁣Get TypeApp for Android ​

**Comment by Gr3gorywolf** [comment]
I usually install them on windows, then format the folder according batocera, create the Autorun and drag the folder to batocera, then if needed I enable the redist installation on wine manager

**Comment by Classicdubs** [comment]
Do you label the folder .pc or .wine ?

---
Chris Vallone
HoP into a BuG!
www.ClassicVWbugs.com

**Comment by Gr3gorywolf** [comment]
.pc, wine is for wine folder system

**Comment by Classicdubs** [comment]
One last question I have for you, sorry to bother you.  Which wine-proton versions are you having the most success with?  There is a big list in the manager, not sure if I should grab them all?  I just have a small handful of games that just don't want to work.

Appreciate you,

Chris 

⁣Get TypeApp for Android ​

**Comment by Gr3gorywolf** [comment]
Proton 9.3 is the perfection

**Comment by Classicdubs** [comment]
Awesome 👍 

⁣Get TypeApp for Android ​
